open_classrooms_core_homepage:
    path:     /
    defaults: { _controller: OpenClassroomsCoreBundle:Advert:menu }

open_classrooms_core_contact:
    path:    /Contact
    defaults: { _controller: OpenClassroomsCoreBundle:Advert:contact }