activite_core_homepage:
    path:     /
    defaults: { _controller: ActiviteCoreBundle:Advert:index }

activite_core_contact:
    path:    /contact
    defaults: { _controller: ActiviteCoreBundle:Advert:contact }